// AttendiQ — All dashboard view renderers
/* ═══════════════════════════════════════════
   VIEWS
═══════════════════════════════════════════ */
var VIEWS={
student:{
  home:function(){return'<div class="page-title">Good morning, Alex 👋</div><div class="page-sub">Monday, Apr 20, 2026</div>'+
    '<div class="alcard ra"><div class="al-ico">⚠️</div><div style="flex:1"><div class="al-title">At Risk — Attendance dropped in 2 courses</div><div class="al-sub">Overall 73%, below the 80% threshold. Biology 101 absence limit reached.</div></div><button class="btn warn sm" onclick="navTo(\'student\',\'alerts\',null)">View →</button></div>'+
    '<div class="mrow"><div class="mc red"><div class="mc-ic">📅</div><div class="mc-v">73%</div><div class="mc-l">Attendance</div><div class="mc-t dn">↓ Class avg 85%</div></div><div class="mc blue"><div class="mc-ic">🎓</div><div class="mc-v">2.6</div><div class="mc-l">Current GPA</div><div class="mc-t nt">→ Stable</div></div><div class="mc green"><div class="mc-ic">✅</div><div class="mc-v">14</div><div class="mc-l">Attended</div><div class="mc-t up">↑ This month</div></div><div class="mc amber"><div class="mc-ic">📚</div><div class="mc-v">5</div><div class="mc-l">Courses</div><div class="mc-t nt">→ Sem 2</div></div></div>'+
    '<div class="g60"><div class="card"><div class="sec-head"><div class="sec-title">Attendance by Course</div><span class="badge amber">2 Below</span></div>'+
    [['CS 101: Intro to Algorithms',88,'green'],['MATH 301: Calculus',62,'red'],['BIO 101: Biology',55,'red'],['HIS 201: World History',79,'amber'],['ENG 102: Technical Writing',93,'green']].map(function(c){return'<div style="margin-bottom:10px"><div style="display:flex;justify-content:space-between;font-size:13px;margin-bottom:4px"><span style="color:var(--t2)">'+c[0]+'</span><span style="font-weight:800;color:'+(c[2]==='green'?'var(--green)':c[2]==='red'?'var(--red)':'var(--amber)')+'">'+c[1]+'%</span></div><div class="prog"><div class="pf '+c[2]+'" data-w="'+c[1]+'"></div></div></div>';}).join('')+
    '</div><div style="display:flex;flex-direction:column;gap:14px"><div class="card"><div class="sec-head"><div class="sec-title">Live Now</div><div class="livepill"><div class="ldot"></div>BUS 202</div></div><div style="font-size:14px;font-weight:800;margin-bottom:3px;color:var(--t1)">Business Ethics</div><div style="font-size:12px;color:var(--t3);margin-bottom:10px">📍 Room 304 · 10:00–11:30 AM</div><div style="font-size:12px;color:var(--green);font-weight:700;margin-bottom:12px">✅ Location verified</div><button class="btn pri ful" onclick="openScan()">⬛ Scan Lecturer\'s QR Code</button></div>'+
    '<div class="tip-card"><div class="tc-inner"><div class="tc-label">Tip of the Day</div><div class="tc-text">Schedule a meeting with your Advisor</div></div><button class="btn ghost sm" onclick="meetingModal()">Book →</button></div></div></div>';},
  courses:function(){return'<div class="page-title">My Courses</div><div class="page-sub">Spring 2026 · 5 enrolled</div><div class="g2">'+
    [['CS 101','Intro to Algorithms','Prof. Adeyemi','Mon/Wed 2PM',88,'B+',true],['MATH 301','Calculus II','Dr. Thompson','Tue/Thu 10AM',62,'C+',false],['BIO 101','Biology','Prof. Okonkwo','Mon/Fri 11AM',55,'C',false],['HIS 201','World History','Dr. Smith','Wed 3PM',79,'B',false],['ENG 102','Technical Writing','Prof. Levi','Thu 1PM',93,'A-',false]]
    .map(function(c){return'<div class="card click"><div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:10px"><div><div style="font-size:10px;font-weight:800;color:var(--blue);text-transform:uppercase;letter-spacing:.08em;margin-bottom:3px">'+c[0]+'</div><div style="font-size:15px;font-weight:800;color:var(--t1)">'+c[1]+'</div><div style="font-size:12px;color:var(--t3);margin-top:2px">'+c[2]+' · '+c[3]+'</div></div>'+(c[6]?'<div class="livepill"><div class="ldot"></div>LIVE</div>':'<span class="badge gray">'+c[5]+'</span>')+'</div><div style="display:flex;justify-content:space-between;font-size:12px;margin-bottom:5px"><span style="color:var(--t3)">Attendance</span><span style="font-weight:800;color:'+(c[4]>=80?'var(--green)':c[4]>=65?'var(--amber)':'var(--red)')+'">'+c[4]+'%</span></div><div class="prog"><div class="pf '+(c[4]>=80?'green':c[4]>=65?'amber':'red')+'" data-w="'+c[4]+'"></div></div>'+(c[6]?'<button class="btn pri ful" style="margin-top:10px" onclick="openScan()">⬛ Scan QR to Mark Attendance</button>':'')+'</div>';}).join('')+'</div>';},
  calendar:function(){return'<div class="page-title">Calendar</div><div class="page-sub">April 2026</div><div class="g60"><div class="card"><div class="sec-head"><div class="sec-title">Today · Apr 20</div><span class="badge blue">4 Sessions</span></div>'+
    [['09:00','Intro to Psychology','Room 304','missed'],['10:00','Business Ethics','Room 304','live'],['11:00','Computer Science 101','Lab 4','upcoming'],['14:00','Calculus II','Lecture Hall B','upcoming']]
    .map(function(s){return'<div style="display:flex;gap:10px;padding:10px 0;border-bottom:1px solid var(--brd);align-items:center"><div style="width:50px;font-size:11px;font-weight:700;color:var(--t4);flex-shrink:0;font-family:var(--mono)">'+s[0]+'</div><div style="flex:1"><div style="font-size:13px;font-weight:700;color:var(--t1)">'+s[1]+'</div><div style="font-size:11px;color:var(--t3)">📍 '+s[2]+'</div></div>'+(s[3]==='live'?'<div class="livepill"><div class="ldot"></div>LIVE</div><button class="btn pri sm" onclick="openScan()">Scan</button>':'<span class="badge '+(s[3]==='missed'?'red':'gray')+'">'+(s[3]==='missed'?'Missed':'Upcoming')+'</span>')+'</div>';}).join('')+
    '</div><div class="card"><div class="sec-head"><div class="sec-title">Heatmap · April</div></div><div class="hmap">'+
    [0,1,2,3,2,1,0,3,2,3,1,2,3,0,2,3,1,2,3,2,'a','l',3,'a',2,2,3,1].map(function(v,i){var bg=v==='a'?'rgba(245,69,106,.45)':v==='l'?'rgba(245,166,35,.5)':v===3?'var(--green)':v===2?'rgba(15,186,129,.4)':v===1?'rgba(15,186,129,.18)':'rgba(255,255,255,.04)';return'<div class="hm-cell" style="background:'+bg+'" title="Apr '+(i+1)+'"></div>';}).join('')+
    '</div><div style="display:flex;gap:10px;margin-top:8px;font-size:10px;color:var(--t4)"><span>🟢 Present</span><span>🟡 Late</span><span>🔴 Absent</span></div></div></div>';},
  alerts:function(){return'<div class="page-title">Alerts & Recommendations</div><div class="page-sub">3 active alerts</div><div class="alcard ra"><div class="al-ico">🚨</div><div style="flex:1"><div class="al-title">BIO 101 — Max absence limit reached</div><div class="al-sub">All 4 allowed absences used. Further absences will penalise your grade.</div><div style="display:flex;gap:8px;margin-top:10px"><button class="btn ghost sm" onclick="toast(\'📧 Email sent to professor\')">Email Prof</button><button class="btn pri sm" onclick="meetingModal()">Schedule Meeting</button></div></div></div>'+
    '<div class="alcard aa"><div class="al-ico">⚠️</div><div><div class="al-title">MATH 301 — Missed 3 consecutive lectures</div><div class="al-sub">Attendance at 62%. Attend next 3 lectures to recover.</div></div></div>'+
    '<div class="sec-head" style="margin-top:16px"><div class="sec-title">Next Steps</div></div><div class="card">'+
    [['📚','Attend next 3 lectures','Mon, Wed, Fri 10AM','Remind'],['👤','Book office hours — Prof. Smith','Openings today','Book'],['📖','Schedule tutoring','Calculus basics review','Find']]
    .map(function(a){return'<div style="display:flex;align-items:center;gap:12px;padding:11px 0;border-bottom:1px solid var(--brd)"><div style="width:34px;height:34px;border-radius:9px;background:var(--su2);display:flex;align-items:center;justify-content:center;font-size:17px;flex-shrink:0">'+a[0]+'</div><div style="flex:1"><div style="font-size:13px;font-weight:700;color:var(--t1)">'+a[1]+'</div><div style="font-size:12px;color:var(--t3)">'+a[2]+'</div></div><button class="btn pri sm" onclick="toast(\'✅ '+a[1]+'\')">'+a[3]+'</button></div>';}).join('')+'</div>';},
  profile:function(){return'<div class="page-title">Profile & Settings</div><div class="page-sub">Manage your account</div><div class="g60"><div class="card"><div style="display:flex;align-items:center;gap:16px;margin-bottom:18px;padding-bottom:18px;border-bottom:1px solid var(--brd)"><div class="profile-av" style="background:var(--blue);color:#fff">AJ</div><div><div style="font-size:20px;font-weight:900;letter-spacing:-.04em;color:var(--t1)">Alex Johnson</div><div style="font-size:12px;color:var(--t3);margin-top:2px">Computer Science · Year 2 · ID: 998210</div><span class="badge red" style="margin-top:6px">At Risk</span></div></div><div class="frow"><div class="fg"><label class="fl">Email</label><input class="fi" value="alex.johnson@uni.edu" readonly></div><div class="fg"><label class="fl">Programme</label><input class="fi" value="B.Sc. Computer Science" readonly></div><div class="fg"><label class="fl">Year</label><input class="fi" value="Year 2" readonly></div><div class="fg"><label class="fl">Advisor</label><input class="fi" value="Advisor Smith" readonly></div></div></div><div style="display:flex;flex-direction:column;gap:14px"><div class="card"><div class="sec-title" style="margin-bottom:12px">Notifications</div>'+
    ['Email alerts','SMS notifications','Weekly digest'].map(function(n){return'<div class="setting-row"><div class="sr-label">'+n+'</div><div class="ntoggle on" onclick="togNtf(this)"></div></div>';}).join('')+'</div><button class="btn ghost ful" onclick="signOut()" style="color:var(--red);border-color:rgba(245,69,106,.25)">🚪 Sign Out</button></div></div>';}
},
lecturer:{
  home:function(){return'<div class="page-title">Good morning, Dr. Vance 🧑‍🏫</div><div class="page-sub">Ready to engage your students today?</div>'+
    '<div class="alcard ga" style="cursor:pointer" onclick="navTo(\'lecturer\',\'create\',null)"><div class="al-ico">📡</div><div style="flex:1"><div class="al-title">Create Today\'s Attendance Session</div><div class="al-sub">Generate a QR code — students scan it with their phones to mark attendance.</div></div><button class="btn grn sm">Create QR →</button></div>'+
    '<div class="mrow"><div class="mc blue"><div class="mc-ic">📡</div><div class="mc-v">76%</div><div class="mc-l">Last Check-in</div><div class="mc-t nt">182/240 scanned</div></div><div class="mc red"><div class="mc-ic">⚠️</div><div class="mc-v">14</div><div class="mc-l">At-Risk</div><div class="mc-t dn">↑ Need attention</div></div><div class="mc green"><div class="mc-ic">📊</div><div class="mc-v">89%</div><div class="mc-l">Semester Avg</div><div class="mc-t up">↑ +2% this month</div></div><div class="mc amber"><div class="mc-ic">🎓</div><div class="mc-v">240</div><div class="mc-l">Enrolled</div><div class="mc-t nt">→ 3 sections</div></div></div>'+
    '<div class="g60"><div class="card"><div class="sec-head"><div class="sec-title">At-Risk Students</div><span class="badge red">14 flagged</span></div><table class="dtab"><thead><tr><th>Student</th><th>Attendance</th><th>Trend</th><th>Action</th></tr></thead><tbody>'+
    [['Marcus Clive',42,'↓ Declining','red'],['Samantha Okonkwo',38,'↓ Critical','red'],['Jordan Smith',65,'→ Stable','amber'],['Amaka Eze',71,'↑ Improving','green']]
    .map(function(s){return'<tr><td><div style="display:flex;align-items:center;gap:8px"><div class="av" style="width:28px;height:28px;font-size:10px">'+s[0].split(' ').map(function(x){return x[0];}).join('')+'</div>'+s[0]+'</div></td><td><span style="font-weight:800;color:'+(s[1]<50?'var(--red)':s[1]<70?'var(--amber)':'var(--green)')+'">'+s[1]+'%</span></td><td><span style="color:'+(s[3]==='green'?'var(--green)':s[3]==='red'?'var(--red)':'var(--amber)')+';font-size:12px">'+s[2]+'</span></td><td><button class="btn ghost sm" onclick="toast(\'📧 Alert sent to '+s[0]+'\')">Alert</button></td></tr>';}).join('')+
    '</tbody></table></div><div style="display:flex;flex-direction:column;gap:14px"><div class="card" style="text-align:center"><div class="sec-title" style="margin-bottom:12px">Last Session</div><div class="donut-w"><svg width="110" height="110" viewBox="0 0 110 110"><circle cx="55" cy="55" r="44" fill="none" stroke="rgba(255,255,255,.05)" stroke-width="12"/><circle cx="55" cy="55" r="44" fill="none" stroke="var(--blue)" stroke-width="12" stroke-dasharray="276" stroke-dashoffset="66" stroke-linecap="round"/></svg><div class="donut-l"><div class="dpct">76%</div><div class="dsub">Scanned</div></div></div><div style="display:flex;justify-content:space-around;margin-top:10px"><div style="text-align:center"><div style="font-size:16px;font-weight:900;color:var(--t1)">182</div><div style="font-size:10px;color:var(--t3)">Present</div></div><div style="text-align:center"><div style="font-size:16px;font-weight:900;color:var(--amber)">12</div><div style="font-size:10px;color:var(--t3)">Late</div></div><div style="text-align:center"><div style="font-size:16px;font-weight:900;color:var(--red)">46</div><div style="font-size:10px;color:var(--t3)">Missing</div></div></div></div><button class="btn grn ful" onclick="navTo(\'lecturer\',\'create\',null)">📡 Create New QR Session</button></div></div>';},
  create:function(){return'<div class="page-title">Create QR Attendance Session</div><div class="page-sub">Set session details and generate a QR code for students to scan</div>'+
    '<div class="qr-setup-grid"><div style="display:flex;flex-direction:column;gap:16px">'+
    '<div class="card"><div class="sec-head"><div class="sec-title">Session Details</div></div>'+
    '<div class="fg"><label class="fl">Course</label><select class="fi" id="qs-course"><option>BUS 202 — Business Ethics &amp; Corporate Responsibility</option><option>CS 101 — Introduction to Algorithms</option><option>MATH 301 — Calculus II</option></select></div>'+
    '<div class="frow"><div class="fg"><label class="fl">Room / Location</label><input class="fi" id="qs-room" value="Room 304" placeholder="e.g. Room 304"></div><div class="fg"><label class="fl">Scan Window</label><select class="fi" id="qs-mins"><option value="5">5 minutes</option><option value="10" selected>10 minutes</option><option value="15">15 minutes</option><option value="20">20 minutes</option><option value="30">30 minutes</option></select></div></div>'+
    '<div class="frow"><div class="fg"><label class="fl">Late Threshold</label><select class="fi"><option>5 mins after start</option><option selected>10 mins after start</option><option>15 mins after start</option></select></div><div class="fg"><label class="fl">Allow Late Check-in</label><select class="fi"><option>Yes — allow late</option><option>No — strict window</option></select></div></div>'+
    '<button class="btn grn ful" style="padding:15px;font-size:14px" onclick="createQR()">⚡ Generate QR Code Now</button></div>'+
    '<div class="qr-stage" id="qrStage" style="display:none"><div class="qr-stage-corner tl"></div><div class="qr-stage-corner tr"></div><div class="qr-stage-corner bl"></div><div class="qr-stage-corner br"></div>'+
    '<div class="qr-canvas-wrap" style="position:relative"><div id="qrCode"></div><div class="qr-scan-line"></div></div>'+
    '<div class="qr-course-name" id="qrName">BUS 202</div><div class="qr-session-meta" id="qrMeta">Room 304</div>'+
    '<div class="qr-countdown idle" id="qrTimer">——:——</div><div class="qr-countdown-sub">Session closes when timer expires</div></div>'+
    '<div class="qr-stage" id="qrEmpty" style="min-height:240px"><div class="qr-empty"><div class="qr-empty-icon">⬛</div><div style="font-size:15px;font-weight:800;color:var(--t1);margin-bottom:6px">No active session</div><p style="font-size:13px;color:var(--t3);line-height:1.6">Fill in details above and click<br><strong style="color:var(--green)">Generate QR Code</strong></p></div></div>'+
    '<div id="qrActions" style="display:none;gap:10px"><button class="btn ghost ful" onclick="regenQR()">🔄 Regenerate QR</button><button class="btn danger ful" onclick="endSession()">⏹ End Session</button></div></div>'+
    '<div style="display:flex;flex-direction:column;gap:14px"><div class="card"><div class="sec-head"><div class="sec-title">Live Check-ins</div><div class="livepill"><div class="ldot"></div><span id="scanCount">0</span> scanned</div></div><div class="feed" id="qrFeed"><div style="font-size:12px;color:var(--t4);text-align:center;padding:28px 0">Generate a QR code to start</div></div></div>'+
    '<div class="card"><div class="sec-title" style="margin-bottom:10px">How it works</div>'+
    ['Fill in course and room details','Click Generate QR Code button','A unique QR code appears below','Show it on screen or projector','Students open AttendiQ and scan','Attendance is logged automatically','Session closes when timer expires']
    .map(function(s,i){return'<div class="step"><div class="step-num">'+(i+1)+'</div><div style="font-size:12px;color:var(--t2)">'+s+'</div></div>';}).join('')+'</div></div></div>';},
  sessions:function(){return'<div class="page-title">My Sessions</div><div class="page-sub">All attendance sessions you have created</div><div class="card">'+
    [['BUS 202','Apr 20, 2026','Room 304',182,240,true],['BUS 202','Apr 18, 2026','Room 304',214,240,false],['CS 101','Apr 17, 2026','Lab 4',88,120,false],['BUS 202','Apr 16, 2026','Room 304',240,240,false],['MATH 301','Apr 15, 2026','Hall B',98,180,false]]
    .map(function(s){return'<div class="session-item '+(s[5]?'active':'')+'"><div style="width:40px;height:40px;border-radius:10px;background:'+(s[5]?'rgba(15,186,129,.15)':'rgba(59,123,248,.1)')+';display:flex;align-items:center;justify-content:center;font-size:18px;flex-shrink:0">'+(s[5]?'📡':'📅')+'</div><div style="flex:1"><div style="display:flex;align-items:center;gap:8px;margin-bottom:2px"><span style="font-size:14px;font-weight:800;color:var(--t1)">'+s[0]+'</span>'+(s[5]?'<div class="livepill" style="font-size:10px;padding:2px 8px"><div class="ldot"></div>ACTIVE</div>':'')+'</div><div style="font-size:12px;color:var(--t3)">'+s[1]+' · '+s[2]+'</div></div><div style="text-align:right;flex-shrink:0"><div style="font-size:16px;font-weight:900;color:var(--t1)">'+Math.round(s[3]/s[4]*100)+'%</div><div style="font-size:11px;color:var(--t3)">'+s[3]+'/'+s[4]+' scanned</div></div><button class="btn ghost sm" onclick="toast(\'📊 Loading report...\')">Report</button></div>';}).join('')+'</div>';},
  students:function(){return'<div class="page-title">Student Roster</div><div class="page-sub">BUS 202 · 240 enrolled</div><div class="card"><table class="dtab"><thead><tr><th>Student</th><th>ID</th><th>Attendance</th><th>GPA</th><th>Risk</th><th>Actions</th></tr></thead><tbody>'+
    [['Marcus Clive','2025-0001',42,1.8,'red'],['Samantha Okonkwo','2025-0002',38,1.6,'red'],['Jordan Smith','2025-0012',65,2.4,'amber'],['Amaka Eze','2025-0015',88,3.4,'green'],['Priya Sharma','2025-0022',92,3.8,'green'],['David Okafor','2025-0030',79,2.9,'green']]
    .map(function(s){return'<tr><td><div style="display:flex;align-items:center;gap:9px"><div class="av" style="width:30px;height:30px;font-size:10px">'+s[0].split(' ').map(function(x){return x[0];}).join('')+'</div><span style="font-weight:700;color:var(--t1)">'+s[0]+'</span></div></td><td style="font-family:var(--mono);font-size:11px;color:var(--t4)">'+s[1]+'</td><td><span style="font-weight:800;color:'+(s[2]<50?'var(--red)':s[2]<70?'var(--amber)':'var(--green)')+'">'+s[2]+'%</span></td><td style="font-weight:700;color:var(--t1)">'+s[3]+'</td><td><span class="badge '+s[4]+'">'+(s[4]==='red'?'At Risk':s[4]==='amber'?'Watch':'Stable')+'</span></td><td><div style="display:flex;gap:5px"><button class="btn ghost sm" onclick="studentProfileModal(\''+s[0]+'\')">Profile</button><button class="btn pri sm" onclick="toast(\'📧 Alert sent to '+s[0]+'\')">Alert</button></div></td></tr>';}).join('')+
    '</tbody></table></div>';},
  analytics:function(){return'<div class="page-title">Analytics</div><div class="page-sub">BUS 202 · Spring 2026</div><div class="mrow"><div class="mc blue"><div class="mc-ic">📊</div><div class="mc-v">82%</div><div class="mc-l">Avg Attendance</div><div class="mc-t up">↑ +4% this month</div></div><div class="mc green"><div class="mc-ic">📈</div><div class="mc-v">B+</div><div class="mc-l">Avg Grade</div><div class="mc-t up">↑ Improving</div></div><div class="mc red"><div class="mc-ic">⚠️</div><div class="mc-v">14</div><div class="mc-l">At-Risk</div><div class="mc-t dn">6% of class</div></div><div class="mc amber"><div class="mc-ic">💡</div><div class="mc-v">83%</div><div class="mc-l">Recovery</div><div class="mc-t up">↑ This sem</div></div></div>'+
    '<div class="g2"><div class="card"><div class="sec-head"><div class="sec-title">Attendance — 14 Weeks</div></div><div class="bchart">'+[72,78,82,75,88,83,79,85,82,87,76,80,82,88].map(function(v,i){return'<div class="bbar '+(i===13?'hi':'')+'" style="height:'+(v-60)+'%"></div>';}).join('')+'</div><div class="bbar-lbls">'+Array.from({length:14},function(_,i){return'<span>W'+(i+1)+'</span>';}).join('')+'</div></div>'+
    '<div class="card"><div class="sec-head"><div class="sec-title">Attendance vs Grade</div></div>'+[['>90%','A',45],['80–90%','B+',88],['70–80%','B−',62],['60–70%','C',30],['<60%','D/F',15]].map(function(r){return'<div style="margin-bottom:10px"><div style="display:flex;justify-content:space-between;font-size:12px;margin-bottom:4px"><span style="color:var(--t3)">'+r[0]+' → <strong style="color:var(--t1)">'+r[1]+'</strong></span><span style="color:var(--t4)">'+r[2]+'</span></div><div class="prog"><div class="pf blue" data-w="'+Math.round(r[2]/240*100)+'"></div></div></div>';}).join('')+'</div></div>';},
  override:function(){return'<div class="page-title">Manual Override</div><div class="page-sub">All changes are logged and reviewed monthly</div>'+
    '<div class="g60"><div class="card"><div class="fg"><label class="fl">Student</label><select class="fi"><option>Jordan Smith (2025-0012)</option><option>Marcus Clive (2025-0001)</option></select></div><div class="fg"><label class="fl">Session</label><select class="fi"><option>BUS 202 — Apr 20, 2026 · 10:00 AM</option></select></div><div class="fg"><label class="fl">New Status</label><div class="fchips"><div class="chip on" onclick="chp(this)">Present</div><div class="chip" onclick="chp(this)">Late</div><div class="chip" onclick="chp(this)">Excused</div><div class="chip" onclick="chp(this)">Absent</div></div></div><div class="fg"><label class="fl">Reason (mandatory)</label><textarea class="fi" placeholder="Describe the reason..."></textarea></div><div class="fchips"><div class="chip" onclick="chp(this)">Device Issue</div><div class="chip" onclick="chp(this)">Medical</div><div class="chip" onclick="chp(this)">Prior Approval</div><div class="chip" onclick="chp(this)">Technical Glitch</div></div><div class="alcard aa" style="margin-bottom:14px"><div class="al-ico" style="font-size:15px">⚠️</div><div class="al-sub" style="font-size:11px">This will be logged with your ID and timestamp and reviewed monthly.</div></div><button class="btn warn ful" onclick="toast(\'✅ Override saved to audit trail\')">Confirm &amp; Log Override</button></div>'+
    '<div class="card"><div class="sec-title" style="margin-bottom:12px">Recent Overrides</div>'+[['Jordan Smith','Present → Late','2h ago'],['Amaka Eze','Absent → Excused','Yesterday']].map(function(o){return'<div style="padding:9px 0;border-bottom:1px solid var(--brd)"><div style="font-size:13px;font-weight:700;color:var(--t1)">'+o[0]+'</div><div style="font-size:12px;color:var(--amber)">'+o[1]+'</div><div style="font-size:11px;color:var(--t4)">'+o[2]+'</div></div>';}).join('')+'</div></div>';},
},
advisor:{
  home:function(){return'<div class="page-title">Good morning, Advisor Smith 📋</div><div class="page-sub">8 students need attention this week</div>'+
    '<div class="mrow"><div class="mc blue"><div class="mc-ic">👥</div><div class="mc-v">20</div><div class="mc-l">Total Advisees</div><div class="mc-t nt">→ Active</div></div><div class="mc red"><div class="mc-ic">🚨</div><div class="mc-v">2</div><div class="mc-l">High Risk</div><div class="mc-t dn">↑ Immediate</div></div><div class="mc amber"><div class="mc-ic">⚠️</div><div class="mc-v">6</div><div class="mc-l">Attention</div><div class="mc-t nt">Monitor</div></div><div class="mc green"><div class="mc-ic">✅</div><div class="mc-v">5</div><div class="mc-l">Improved</div><div class="mc-t up">↑ This month</div></div></div>'+
    '<div class="g60"><div class="card"><div class="sec-head"><div class="sec-title">Priority Alerts</div><span class="badge red">8 this week</span></div>'+
    [['Marcus Clive','Bio 200 · Freshman','Grade below 60% in Math 101.','Yesterday','red'],['Samantha Okechuku','Bio 200 · Freshman','Absent 5 consecutive days.','Yesterday','red'],['Jordan Smith','CS 101 · Year 2','Attendance dropped 20% in 2 weeks.','2 days ago','amber']]
    .map(function(s){return'<div style="display:flex;gap:10px;padding:12px 0;border-bottom:1px solid var(--brd)"><div class="av" style="width:38px;height:38px;font-size:13px">'+s[0].split(' ').map(function(x){return x[0];}).join('')+'</div><div style="flex:1"><div style="display:flex;justify-content:space-between"><span style="font-size:14px;font-weight:800;color:var(--t1)">'+s[0]+'</span><span class="badge '+s[4]+'">'+(s[4]==='red'?'At Risk':'Attention')+'</span></div><div style="font-size:11px;color:var(--t3)">'+s[1]+'</div><div style="font-size:12px;color:var(--t3);margin-top:4px">'+s[2]+'</div><div style="display:flex;gap:7px;margin-top:9px"><button class="btn pri sm" onclick="studentProfileModal(\''+s[0]+'\')">View Profile</button><button class="btn ghost sm" onclick="renderView(\'advisor\',\'intervene\')">Intervene</button></div></div></div>';}).join('')+'</div>'+
    '<div style="display:flex;flex-direction:column;gap:14px"><div class="card"><div class="sec-title" style="margin-bottom:12px">Caseload</div>'+[['Stable',12,'green'],['Attention',6,'amber'],['At Risk',2,'red']].map(function(r){return'<div style="margin-bottom:10px"><div style="display:flex;justify-content:space-between;font-size:12px;margin-bottom:4px"><span style="color:var(--t3)">'+r[0]+'</span><span style="font-weight:800;color:'+(r[2]==='green'?'var(--green)':r[2]==='red'?'var(--red)':'var(--amber)')+'">'+r[1]+'/20</span></div><div class="prog"><div class="pf '+r[2]+'" data-w="'+(r[1]/20*100)+'"></div></div></div>';}).join('')+'</div>'+
    '<div class="card" style="text-align:center"><div style="font-size:32px;font-weight:900;color:var(--green);letter-spacing:-.04em">83%</div><div style="font-size:12px;color:var(--t3);margin-bottom:10px">Intervention Success</div><div class="spark">'+[40,52,60,70,64,75,83].map(function(v,i){return'<div class="sb '+(i===6?'hi':'')+'" style="height:'+v+'%"></div>';}).join('')+'</div></div>'+
    '<button class="btn pri ful" onclick="renderView(\'advisor\',\'intervene\')">+ Log Intervention</button></div></div>';},
  advisees:function(){return'<div class="page-title">My Advisees</div><div class="page-sub">20 students in your caseload</div><div class="card"><table class="dtab"><thead><tr><th>Student</th><th>Programme</th><th>Attendance</th><th>GPA</th><th>Status</th><th>Actions</th></tr></thead><tbody>'+
    [['Marcus Clive','Bio 200 · Yr 1',42,1.8,'red'],['Samantha Okechuku','Bio 200 · Yr 1',38,1.6,'red'],['Jordan Smith','CS 101 · Yr 2',65,2.4,'amber'],['Amaka Eze','BUS 202 · Yr 2',88,3.4,'green'],['Priya Sharma','CHEM · Yr 2',92,3.8,'green'],['David Okafor','MATH · Yr 1',79,2.9,'green']]
    .map(function(s){return'<tr><td><div style="display:flex;align-items:center;gap:9px"><div class="av" style="width:30px;height:30px;font-size:10px">'+s[0].split(' ').map(function(x){return x[0];}).join('')+'</div><span style="font-weight:700;color:var(--t1)">'+s[0]+'</span></div></td><td style="font-size:12px;color:var(--t3)">'+s[1]+'</td><td><span style="font-weight:800;color:'+(s[2]<50?'var(--red)':s[2]<70?'var(--amber)':'var(--green)')+'">'+s[2]+'%</span></td><td style="font-weight:700;color:var(--t1)">'+s[3]+'</td><td><span class="badge '+s[4]+'">'+(s[4]==='red'?'At Risk':s[4]==='amber'?'Watch':'Stable')+'</span></td><td><div style="display:flex;gap:5px"><button class="btn ghost sm" onclick="studentProfileModal(\''+s[0]+'\')">Profile</button><button class="btn pri sm" onclick="renderView(\'advisor\',\'intervene\')">Intervene</button></div></td></tr>';}).join('')+'</tbody></table></div>';},
  alerts:function(){return'<div class="page-title">Priority Alerts</div><div class="page-sub">2 high-risk students require immediate action</div>'+
    [['Marcus Clive','Absent 5 consecutive days. Grades declined in Data Structure (55%) and Calc II (48%).'],['Samantha Okechuku','5 unexcused absences. GPA dropped from 3.2 to 1.8. No response to emails.']]
    .map(function(s){return'<div class="alcard ra"><div class="al-ico">🚨</div><div style="flex:1"><div class="al-title">'+s[0]+' — High Risk</div><div class="al-sub">'+s[1]+'</div><div style="display:flex;gap:8px;margin-top:10px"><button class="btn pri sm" onclick="studentProfileModal(\''+s[0]+'\')">View Profile</button><button class="btn ghost sm" onclick="renderView(\'advisor\',\'intervene\')">Intervene</button><button class="btn danger sm" onclick="toast(\'📢 Escalated to Dean\')">Escalate</button></div></div></div>';}).join('');},
  intervene:function(){return'<div class="page-title">Log Intervention</div><div class="page-sub">Record your action and create an action plan</div>'+
    '<div class="g60"><div class="card"><div class="fg"><label class="fl">Student</label><select class="fi"><option>Marcus Clive (High Risk)</option><option>Samantha Okechuku (High Risk)</option><option>Jordan Smith (Attention)</option></select></div><div class="fg"><label class="fl">Type</label><select class="fi"><option>Meeting</option><option>Email Follow-up</option><option>Phone Call</option><option>Referral</option></select></div><div class="frow"><div class="fg"><label class="fl">Date</label><input class="fi" type="date" value="2026-04-20"></div><div class="fg"><label class="fl">Advisor</label><select class="fi"><option>Advisor Smith (You)</option></select></div></div><div class="fg"><label class="fl">Notes</label><textarea class="fi" placeholder="Discussion, concerns, agreed steps..."></textarea></div><div class="fg"><label class="fl">Follow-up Date</label><input class="fi" type="date" value="2026-04-30"></div><div class="fchips"><div class="chip" onclick="chp(this)">Reduce load</div><div class="chip" onclick="chp(this)">Tutoring</div><div class="chip" onclick="chp(this)">Accommodations</div><div class="chip" onclick="chp(this)">Counselling</div></div><button class="btn pri ful" onclick="toast(\'✅ Intervention saved. Follow-up Apr 30.\')">Save Record</button></div>'+
    '<div class="card"><div style="display:flex;align-items:center;gap:12px;margin-bottom:12px"><div class="av" style="width:44px;height:44px;font-size:16px;font-weight:900">MC</div><div><div style="font-weight:900;font-size:16px;color:var(--t1)">Marcus Clive</div><div style="font-size:12px;color:var(--t3)">CS · Year 2</div><span class="badge red" style="margin-top:5px">High Risk</span></div></div><div class="divl"></div><div style="font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:.09em;color:var(--amber);margin-bottom:6px">Why Flagged</div><div style="font-size:12px;color:var(--t3);line-height:1.6;margin-bottom:14px">Absent 5 days. Grades declined in Data Structure (55%) and Calc II (48%).</div><div class="risk-labels"><span>HIGH</span><span>MODERATE</span><span>LOW</span></div><div class="risk-track"><div class="risk-thumb" style="left:15%"></div></div><div style="display:flex;gap:8px;margin-top:12px"><div class="sp-stat"><div class="sp-stat-v" style="color:var(--red)">42%</div><div class="sp-stat-l">Attendance</div></div><div class="sp-stat"><div class="sp-stat-v">1.8</div><div class="sp-stat-l">GPA</div></div></div></div></div>';},
  analytics:function(){return'<div class="page-title">Advising Analytics</div><div class="page-sub">Spring 2026 caseload performance</div><div class="mrow"><div class="mc green"><div class="mc-ic">📈</div><div class="mc-v">83%</div><div class="mc-l">Success Rate</div><div class="mc-t up">↑ +8% vs last sem</div></div><div class="mc blue"><div class="mc-ic">📅</div><div class="mc-v">24</div><div class="mc-l">Meetings</div><div class="mc-t up">↑ This month</div></div><div class="mc amber"><div class="mc-ic">⏱️</div><div class="mc-v">2.4d</div><div class="mc-l">Avg Response</div><div class="mc-t nt">Target &lt;2 days</div></div><div class="mc red"><div class="mc-ic">🎯</div><div class="mc-v">5</div><div class="mc-l">Recovered</div><div class="mc-t up">↑ Best month</div></div></div>'+
    '<div class="g2"><div class="card"><div class="sec-head"><div class="sec-title">Outcomes — 7 Months</div></div><div class="bchart">'+[60,65,70,75,68,80,83].map(function(v,i){return'<div class="bbar gb '+(i===6?'hi':'')+'" style="height:'+(v-52)+'%"></div>';}).join('')+'</div><div class="bbar-lbls"><span>Sep</span><span>Oct</span><span>Nov</span><span>Dec</span><span>Jan</span><span>Feb</span><span>Mar</span></div></div><div class="card"><div class="sec-head"><div class="sec-title">Risk Distribution</div></div>'+[['Stable',12,'green'],['Attention',6,'amber'],['At Risk',2,'red']].map(function(r){return'<div style="margin-bottom:10px"><div style="display:flex;justify-content:space-between;font-size:12px;margin-bottom:4px"><span style="color:var(--t3)">'+r[0]+'</span><span style="font-weight:800;color:'+(r[2]==='green'?'var(--green)':r[2]==='red'?'var(--red)':'var(--amber)')+'">'+r[1]+'</span></div><div class="prog"><div class="pf '+r[2]+'" data-w="'+(r[1]/20*100)+'"></div></div></div>';}).join('')+'</div></div>';},
  profile:function(){return'<div class="page-title">My Profile</div><div class="page-sub">Account and preferences</div><div class="g60"><div class="card"><div style="display:flex;align-items:center;gap:16px;margin-bottom:18px;padding-bottom:18px;border-bottom:1px solid var(--brd)"><div class="profile-av" style="background:var(--amber);color:#fff">AS</div><div><div style="font-size:20px;font-weight:900;color:var(--t1)">Advisor Smith</div><div style="font-size:12px;color:var(--t3)">Academic Advisor · Student Affairs</div><span class="badge blue" style="margin-top:6px">20 Advisees</span></div></div><div class="frow"><div class="fg"><label class="fl">Email</label><input class="fi" value="advisor.smith@uni.edu" readonly></div><div class="fg"><label class="fl">Office</label><input class="fi" value="Student Services, Rm 204" readonly></div></div></div><div style="display:flex;flex-direction:column;gap:14px"><div class="card"><div class="sec-title" style="margin-bottom:12px">Alert Preferences</div>'+['New at-risk alerts','Daily digest','Meeting reminders'].map(function(n){return'<div class="setting-row"><div class="sr-label">'+n+'</div><div class="ntoggle on" onclick="togNtf(this)"></div></div>';}).join('')+'</div><button class="btn ghost ful" onclick="signOut()" style="color:var(--red);border-color:rgba(245,69,106,.25)">🚪 Sign Out</button></div></div>';}
},
admin:{
  home:function(){return'<div class="page-title">Department Overview 🏛</div><div class="page-sub">Computer Science · Spring 2026</div><div class="mrow"><div class="mc blue"><div class="mc-ic">🎓</div><div class="mc-v">1,240</div><div class="mc-l">Total Students</div><div class="mc-t up">↑ +3%</div></div><div class="mc green"><div class="mc-ic">📊</div><div class="mc-v">81%</div><div class="mc-l">Avg Attendance</div><div class="mc-t up">↑ On track</div></div><div class="mc red"><div class="mc-ic">⚠️</div><div class="mc-v">156</div><div class="mc-l">At Risk</div><div class="mc-t dn">Across all courses</div></div><div class="mc amber"><div class="mc-ic">📚</div><div class="mc-v">32</div><div class="mc-l">Courses</div><div class="mc-t nt">→ 8 tracked</div></div></div>'+
    '<div class="g60"><div class="card"><div class="sec-head"><div class="sec-title">Course Performance</div></div><table class="dtab"><thead><tr><th>Course</th><th>Lecturer</th><th>Enrolled</th><th>Attend.</th><th>Risk</th></tr></thead><tbody>'+
    [['CS 101','Intro to Algorithms','Prof. Adeyemi',240,88,12],['MATH 301','Calculus II','Dr. Thompson',180,74,24],['BUS 202','Business Ethics','Dr. Vance',240,82,18],['CHEM 105','Organic Chemistry','Prof. Okonkwo',120,69,30],['ENG 102','Technical Writing','Prof. Levi',160,91,5]]
    .map(function(c){return'<tr><td><div style="font-size:10px;color:var(--blue);font-weight:800;text-transform:uppercase">'+c[0]+'</div><div style="font-size:13px;color:var(--t1)">'+c[1]+'</div></td><td style="font-size:12px;color:var(--t3)">'+c[2]+'</td><td style="font-weight:700;color:var(--t1)">'+c[3]+'</td><td><span style="font-weight:800;color:'+(c[4]>=80?'var(--green)':c[4]>=70?'var(--amber)':'var(--red)')+'">'+c[4]+'%</span></td><td><span class="badge '+(c[5]>=25?'red':c[5]>=15?'amber':'green')+'">'+c[5]+'</span></td></tr>';}).join('')+
    '</tbody></table></div><div style="display:flex;flex-direction:column;gap:14px"><div class="card"><div class="sec-head"><div class="sec-title">14-Week Trend</div></div><div class="bchart">'+[74,76,80,78,82,79,83,81,85,80,83,87,84,81].map(function(v,i){return'<div class="bbar '+(i===13?'hi':'')+'" style="height:'+(v-68)+'%"></div>';}).join('')+'</div><div class="bbar-lbls">'+Array.from({length:14},function(_,i){return'<span>W'+(i+1)+'</span>';}).join('')+'</div></div><button class="btn teal-b ful" onclick="openCreateAccount()">➕ Create New Account</button></div></div>';},
  courses:function(){return'<div class="page-title">All Courses</div><div class="page-sub">32 active courses</div><div class="card" style="padding:40px;text-align:center;color:var(--t3)">Full course management — use department filters to drill down</div>';},
  students:function(){return'<div class="page-title">All Students</div><div class="page-sub">1,240 students across all programmes</div><div class="card"><table class="dtab"><thead><tr><th>Student</th><th>Programme</th><th>Year</th><th>Attendance</th><th>GPA</th><th>Risk</th></tr></thead><tbody>'+[['Alex Johnson','Comp. Sci.',2,73,2.6,'amber'],['Marcus Clive','Biology',1,42,1.8,'red'],['Amaka Eze','Business',2,88,3.4,'green'],['Priya Sharma','Chemistry',2,92,3.8,'green'],['Jordan Smith','Comp. Sci.',2,65,2.4,'amber'],['David Okafor','Mathematics',1,79,2.9,'green']].map(function(s){return'<tr><td><div style="display:flex;align-items:center;gap:9px"><div class="av" style="width:30px;height:30px;font-size:10px">'+s[0].split(' ').map(function(x){return x[0];}).join('')+'</div><span style="font-weight:700;color:var(--t1)">'+s[0]+'</span></div></td><td style="font-size:12px;color:var(--t3)">'+s[1]+'</td><td style="font-size:12px;color:var(--t3)">Year '+s[2]+'</td><td><span style="font-weight:800;color:'+(s[3]<50?'var(--red)':s[3]<70?'var(--amber)':'var(--green)')+'">'+s[3]+'%</span></td><td style="font-weight:700;color:var(--t1)">'+s[4]+'</td><td><span class="badge '+s[5]+'">'+(s[5]==='red'?'At Risk':s[5]==='amber'?'Watch':'Stable')+'</span></td></tr>';}).join('')+'</tbody></table></div>';},
  reports:function(){return'<div class="page-title">Reports</div><div class="page-sub">Generate and export analytics reports</div><div class="g2">'+[['📊','Weekly Attendance Report','All courses · This week','blue'],['⚠️','At-Risk Student Report','156 students flagged','red'],['🎓','Graduation Risk Analysis','Predictive model · 2026','amber'],['📈','Semester Performance','Comparative analysis','green']].map(function(r){return'<div class="report-card" onclick="toast(\'📄 Generating '+r[1]+'...\')"><div style="width:44px;height:44px;border-radius:11px;background:rgba('+(r[3]==='blue'?'59,123,248':r[3]==='red'?'245,69,106':r[3]==='amber'?'245,166,35':'15,186,129')+',.12);display:flex;align-items:center;justify-content:center;font-size:20px;margin-bottom:12px">'+r[0]+'</div><div style="font-size:15px;font-weight:800;color:var(--t1);margin-bottom:4px">'+r[1]+'</div><div style="font-size:12px;color:var(--t3);margin-bottom:14px">'+r[2]+'</div><div style="display:flex;gap:8px"><button class="btn pri sm" onclick="event.stopPropagation();toast(\'📄 PDF generating...\')">PDF</button><button class="btn ghost sm" onclick="event.stopPropagation();toast(\'📊 CSV downloading...\')">CSV</button></div></div>';}).join('')+'</div>';},
  accounts:accountsView,
  settings:function(){return'<div class="page-title">Settings</div><div class="page-sub">System configuration</div><div class="g2"><div class="card"><div class="sec-title" style="margin-bottom:14px">Attendance Policies</div>'+[['Min. attendance threshold','80%'],['Consecutive absence alert','3 days'],['Late check-in window','10 minutes'],['QR session default','10 minutes']].map(function(s){return'<div class="setting-row"><div><div class="sr-label">'+s[0]+'</div></div><button class="btn ghost sm" onclick="toast(\'✏️ Editing...\')">'+s[1]+'</button></div>';}).join('')+'</div><div class="card"><div class="sec-title" style="margin-bottom:14px">Notifications</div>'+['Auto-alert students on absence','Auto-alert advisors','Weekly digest to dean','SMS critical alerts'].map(function(n){return'<div class="setting-row"><div class="sr-label">'+n+'</div><div class="ntoggle on" onclick="togNtf(this)"></div></div>';}).join('')+'</div><div class="card"><div class="sec-title" style="margin-bottom:12px">Admin Account</div><div class="frow"><div class="fg"><label class="fl">Name</label><input class="fi" value="Dean Williams" readonly></div><div class="fg"><label class="fl">Email</label><input class="fi" value="dean.williams@uni.edu" readonly></div></div><button class="btn ghost ful" onclick="signOut()" style="color:var(--red);border-color:rgba(245,69,106,.25)">🚪 Sign Out</button></div></div>';}
},
provost:{
  home:function(){return'<div class="page-title">Good morning, Provost Adeyemi 🎖️</div><div class="page-sub">University-wide overview · Monday, Apr 20, 2026</div>'+
    '<div class="mrow"><div class="mc blue"><div class="mc-ic">🎓</div><div class="mc-v">12,400</div><div class="mc-l">Total Students</div><div class="mc-t up">↑ +340 this term</div></div><div class="mc green"><div class="mc-ic">📊</div><div class="mc-v">84%</div><div class="mc-l">University Avg.</div><div class="mc-t up">↑ Ahead of target</div></div><div class="mc red"><div class="mc-ic">⚠️</div><div class="mc-v">1,420</div><div class="mc-l">At-Risk Uni-Wide</div><div class="mc-t dn">11.5% of total</div></div><div class="mc amber"><div class="mc-ic">🏫</div><div class="mc-v">8</div><div class="mc-l">Departments</div><div class="mc-t nt">→ All reporting</div></div></div>'+
    '<div class="g60"><div class="card"><div class="sec-head"><div class="sec-title">Department Performance</div></div><table class="dtab"><thead><tr><th>Department</th><th>Students</th><th>Avg. Attend.</th><th>At Risk</th><th>Trend</th></tr></thead><tbody>'+
    [['Computer Science',1240,81,156,'↑'],['Mathematics',980,78,180,'→'],['Biology',860,83,120,'↑'],['Business',1500,86,98,'↑'],['Chemistry',640,72,210,'↓'],['English',720,88,60,'↑'],['Physics',480,75,140,'→'],['Engineering',1100,82,120,'↑']]
    .map(function(d){return'<tr><td style="font-weight:700;color:var(--t1)">'+d[0]+'</td><td style="color:var(--t2)">'+d[1].toLocaleString()+'</td><td><span style="font-weight:800;color:'+(d[2]>=82?'var(--green)':d[2]>=75?'var(--amber)':'var(--red)')+'">'+d[2]+'%</span></td><td><span class="badge '+(d[3]>=180?'red':d[3]>=130?'amber':'green')+'">'+d[3]+'</span></td><td style="font-size:18px">'+(d[4]==='↑'?'📈':d[4]==='↓'?'📉':'➡️')+'</td></tr>';}).join('')+
    '</tbody></table></div><div style="display:flex;flex-direction:column;gap:14px"><div class="card" style="text-align:center"><div class="sec-title" style="margin-bottom:12px">University Attendance</div><div class="donut-w"><svg width="110" height="110" viewBox="0 0 110 110"><circle cx="55" cy="55" r="44" fill="none" stroke="rgba(255,255,255,.05)" stroke-width="12"/><circle cx="55" cy="55" r="44" fill="none" stroke="#14C882" stroke-width="12" stroke-dasharray="276" stroke-dashoffset="44" stroke-linecap="round"/></svg><div class="donut-l"><div class="dpct" style="color:#14C882">84%</div><div class="dsub">Uni. Avg.</div></div></div><div style="display:flex;justify-content:space-around;margin-top:10px"><div style="text-align:center"><div style="font-size:14px;font-weight:900;color:var(--green)">10,980</div><div style="font-size:10px;color:var(--t3)">On Track</div></div><div style="text-align:center"><div style="font-size:14px;font-weight:900;color:var(--red)">1,420</div><div style="font-size:10px;color:var(--t3)">At Risk</div></div></div></div>'+
    '<button class="btn teal-b ful" onclick="openCreateAccount()">➕ Create New Account</button></div></div>';},
  departments:function(){return'<div class="page-title">Departments</div><div class="page-sub">8 departments under university oversight</div><div class="g2">'+
    [['Computer Science','Dr. Williams',1240,22,5,81,'blue'],['Mathematics','Prof. Osei',980,18,4,78,'amber'],['Biology','Dr. Okonkwo',860,16,3,83,'green'],['Business','Prof. Mensah',1500,28,6,86,'green'],['Chemistry','Dr. Adesola',640,12,3,72,'red'],['English','Prof. Levi',720,14,3,88,'green'],['Physics','Dr. Fashola',480,10,2,75,'amber'],['Engineering','Prof. Chukwu',1100,24,5,82,'green']]
    .map(function(d){return'<div class="card click" onclick="toast(\'🏫 Opening '+d[0]+' department...\')"><div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:10px"><div><div style="font-size:16px;font-weight:900;color:var(--t1)">'+d[0]+'</div><div style="font-size:12px;color:var(--t3)">Head: '+d[1]+'</div></div><span style="font-size:22px;font-weight:900;color:'+(d[6]==='green'?'var(--green)':d[6]==='red'?'var(--red)':'var(--amber)')+'">'+d[6]==='green'?d[5]:d[5]+'%</span></div><div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;margin-bottom:10px"><div style="background:var(--su2);border-radius:8px;padding:8px;text-align:center"><div style="font-size:15px;font-weight:900;color:var(--t1)">'+d[2]+'</div><div style="font-size:10px;color:var(--t3)">Students</div></div><div style="background:var(--su2);border-radius:8px;padding:8px;text-align:center"><div style="font-size:15px;font-weight:900;color:var(--t1)">'+d[3]+'</div><div style="font-size:10px;color:var(--t3)">Lecturers</div></div><div style="background:var(--su2);border-radius:8px;padding:8px;text-align:center"><div style="font-size:15px;font-weight:900;color:var(--t1)">'+d[4]+'</div><div style="font-size:10px;color:var(--t3)">Advisors</div></div></div><div class="prog"><div class="pf '+d[6]+'" data-w="'+d[5]+'"></div></div></div>';}).join('')+'</div>';},
  faculty:function(){return'<div class="page-title">Faculty & Staff</div><div class="page-sub">All lecturers, advisors and administrative staff</div><div class="mrow"><div class="mc blue"><div class="mc-ic">🧑‍🏫</div><div class="mc-v">144</div><div class="mc-l">Lecturers</div><div class="mc-t up">↑ +8 this year</div></div><div class="mc green"><div class="mc-ic">📋</div><div class="mc-v">31</div><div class="mc-l">Advisors</div><div class="mc-t nt">→ Full coverage</div></div><div class="mc amber"><div class="mc-ic">🏛</div><div class="mc-v">12</div><div class="mc-l">Admins</div><div class="mc-t nt">→ All depts</div></div><div class="mc red"><div class="mc-ic">📝</div><div class="mc-v">3</div><div class="mc-l">Pending Reviews</div><div class="mc-t dn">Action needed</div></div></div>'+
    '<div class="card"><div class="sec-head"><div class="sec-title">Faculty by Department</div><button class="btn teal-b sm" onclick="openCreateAccount()">➕ Add Staff</button></div><table class="dtab"><thead><tr><th>Department</th><th>Lecturers</th><th>Advisors</th><th>Dept. Head</th><th>Avg Rating</th></tr></thead><tbody>'+
    [['Computer Science',22,5,'Dr. Williams',4.6],['Mathematics',18,4,'Prof. Osei',4.3],['Biology',16,3,'Dr. Okonkwo',4.5],['Business',28,6,'Prof. Mensah',4.7],['Chemistry',12,3,'Dr. Adesola',4.1],['English',14,3,'Prof. Levi',4.8],['Physics',10,2,'Dr. Fashola',4.2],['Engineering',24,5,'Prof. Chukwu',4.4]]
    .map(function(d){return'<tr><td style="font-weight:700;color:var(--t1)">'+d[0]+'</td><td>'+d[1]+'</td><td>'+d[2]+'</td><td style="font-size:12px;color:var(--t3)">'+d[3]+'</td><td><span style="font-weight:800;color:'+(d[4]>=4.5?'var(--green)':d[4]>=4.2?'var(--amber)':'var(--red)')+'">⭐ '+d[4]+'</span></td></tr>';}).join('')+'</tbody></table></div>';},
  reports:function(){return'<div class="page-title">Strategic Reports</div><div class="page-sub">University-level executive analytics</div><div class="mrow"><div class="mc green"><div class="mc-ic">📊</div><div class="mc-v">84%</div><div class="mc-l">Uni. Attendance</div><div class="mc-t up">↑ +3% YoY</div></div><div class="mc blue"><div class="mc-ic">🎓</div><div class="mc-v">83%</div><div class="mc-l">Retention Rate</div><div class="mc-t up">↑ +4% YoY</div></div><div class="mc amber"><div class="mc-ic">📈</div><div class="mc-v">76%</div><div class="mc-l">Graduation Rate</div><div class="mc-t up">↑ On target</div></div><div class="mc red"><div class="mc-ic">💰</div><div class="mc-v">11.5%</div><div class="mc-l">At-Risk Rate</div><div class="mc-t up">↓ vs 14% last yr</div></div></div>'+
    '<div class="g2"><div class="card"><div class="sec-head"><div class="sec-title">Attendance — 12 Months</div></div><div class="bchart">'+[76,78,80,79,82,81,83,82,84,83,85,84].map(function(v,i){return'<div class="bbar '+(i===11?'hi':'')+'" style="height:'+(v-70)+'%;background:'+(i===11?'var(--teal)':'rgba(20,200,130,.2)')+'"></div>';}).join('')+'</div><div class="bbar-lbls"><span>M</span><span>J</span><span>J</span><span>A</span><span>S</span><span>O</span><span>N</span><span>D</span><span>J</span><span>F</span><span>M</span><span>A</span></div></div>'+
    '<div class="card"><div class="sec-head"><div class="sec-title">Export Reports</div></div>'+[['📄','University Annual Report'],['📊','Attendance Analytics'],['⚠️','At-Risk Report'],['🎓','Retention Analysis']].map(function(r){return'<div class="setting-row"><div class="sr-label">'+r[1]+'</div><button class="btn ghost sm" onclick="toast(\''+r[0]+' Generating '+r[1]+'...\')">'+r[0]+' Export</button></div>';}).join('')+'</div></div>';},
  accounts:accountsView,
  settings:function(){return'<div class="page-title">Provost Settings</div><div class="page-sub">University-level configuration</div><div class="g2"><div class="card"><div class="sec-title" style="margin-bottom:14px">University Policies</div>'+[['Min. attendance threshold','80%'],['At-risk escalation trigger','3 absences'],['QR session window','10 minutes'],['Retention alert threshold','70%']].map(function(s){return'<div class="setting-row"><div class="sr-label">'+s[0]+'</div><button class="btn ghost sm" onclick="toast(\'✏️ Editing...\')">'+s[1]+'</button></div>';}).join('')+'</div><div class="card"><div class="sec-title" style="margin-bottom:14px">Executive Notifications</div>'+['Weekly university report','Department alerts','Critical escalation','Quarterly board digest'].map(function(n){return'<div class="setting-row"><div class="sr-label">'+n+'</div><div class="ntoggle on" onclick="togNtf(this)"></div></div>';}).join('')+'</div><div class="card"><div class="sec-title" style="margin-bottom:12px">My Account</div><div class="frow"><div class="fg"><label class="fl">Name</label><input class="fi" value="Provost Adeyemi" readonly></div><div class="fg"><label class="fl">Email</label><input class="fi" value="provost@uni.edu" readonly></div></div><button class="btn ghost ful" onclick="signOut()" style="color:var(--red);border-color:rgba(245,69,106,.25)">🚪 Sign Out</button></div></div>';}
}
};
